### ISSUE TITLE
add a jammer detector

### ISSUE THREAD

**Issue by 0x32bit** [MXZZ/Netgotchi#14]
hi, i've been testing this firmware for 1 hours, i have a jammer that jam 2.4GHZ wifi devices, but it doesn't detect. instead the netgotchi just tells me "disconnectted" is it really possible to add jammer detector? it would be great imo. >-<

**Comment by itsOwen** [comment]
I guess the WiFi chip in esp32 doesn't provide the low-level RF signal analysis capabilities needed for proper jammer detection. While we can try monitoring for sudden disconnections combined with noise level analysis, it wouldn't be reliable enough to serve as a true jammer detector without additional specialized RF hardware but yea not sure could be possible. Wait for @MXZZ to reply.

**Comment by MXZZ** [comment]
yes I need to agree with @itsOwen , I don't plan to add this feature because it will need to switch netgotchi in promisc mode and it will defy the purpose to monitor the network. 
the only way I could do it is to introduce this in "Netgotchi Pro" loaders , where it would there that loads different "netgotchi firmware" with different behaviours
currently there is Netgotchi, TextGotchi, ControlGotchi and Deauthergotchi (wip)
